# Generated by Django 4.2.4 on 2023-08-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
