# Generated by Django 4.2.4 on 2023-08-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='Bgroup',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
