# Generated by Django 4.2.4 on 2023-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_course_student_bgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
