# Generated by Django 4.2.4 on 2023-08-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_student_gender_alter_student_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Bgroup',
            new_name='bgroup',
        ),
    ]
